### ISSUE TITLE
Why Python 2.7 

### ISSUE THREAD

**Issue by oltipreka** [BlazingDB/Welcome_to_BlazingSQL_Notebooks#48]
Hello, 

I just bump into app.blazingsql.com and generally it seems a great instrument. 

However, I don't get why the default version is **Python 2.7**. 

Is there a way to upgrade to **Python 3.7** or above?

**Comment by drabastomek** [comment]
Hi @oltipreka.

I just checked and the version of Python in notebooks with `rapids-stable` and `rapids-nightly` is 3.8.5.

```python
from platform import python_version
print(python_version())
```

If you check with `!python --version` it will indeed show 2.7 but that then defaults to the Python environment installed in the native image and we do not update this.
